apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: producer
        image: producer
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"